name: Milestone 2 - CI/CD

on:
  push:
    branches: ["main"]
    tags: ["v*"] # Triggers on semantic version tags
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pytest
          pip install -r module3/milestone2/requirements.txt

      - name: Run tests
        # Pipeline must fail if tests fail
        run: pytest module3/milestone2/tests

  build-and-deploy:
    name: Build and Push to Registry
    needs: test # Ensures build only happens if tests pass
    if: startsWith(github.ref, 'refs/tags/v') # Only deploy on version tags
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        # Authenticate using the secret added to GitHub
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker
        # Required to push to GCP registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Docker Build and Push
        run: |
          # Use your specific registry path
          IMAGE_PATH=us-central1-docker.pkg.dev/nih-cl-odss-ojagtd-5340/ml-models/milestone2-iris:${{ github.ref_name }}
          docker build -t $IMAGE_PATH -f module3/milestone2/Dockerfile module3/milestone2
          docker push $IMAGE_PATH # Push with semantic version tag